export default interface Style {
  flexDirection?: string
  alignItems?: string
  justifyContent?: string
  marginBottom?: string
  marginRight?: string
  marginLeft?: string
  marginTop?: string
  margin?: string
  paddingBottom?: string
  paddingRight?: string
  paddingLeft?: string
  paddingTop?: string
  padding?: string
  backgroundColor?: string
  backgroundImg?: string
  backgroundSize?: string
  borderBottom?: string
  borderRight?: string
  borderLeft?: string
  borderTop?: string
  borderRadius?: string
  border?: string
  color?: string
  height?: string
  width?: string
  fontSize?: string
  fontWeight?: string
  outline?: string
  cursor?: string
  display?: string
  maxWidth?: string
  maxHeight?: string
  textAlign?: string
  hover?: Style
  active?: Style
  lgStyle?: Style
  mdStyle?: Style
  smStyle?: Style
  xsStyle?: Style
}